### ISSUE TITLE
Add new translations from the Laravel framework

### ISSUE THREAD

**Issue by buismaarten** [liamseys/laravel-dutch-translations#2]
Based on the translation file in the Laravel framework, the following changes could be added:
- https://github.com/laravel/framework/commit/641f5a6b459f666d1a67667f4deb63ae8a327893
- https://github.com/laravel/framework/commit/2f8b95ae59712f52778a1cb35addaa9fbf6d891b

**Comment by liamseys** [comment]
@buismaarten Thanks, I've added them!
